### ISSUE TITLE
6张A40卡并行微调Qwen-14B-chat，推理时报错

### ISSUE THREAD

**Issue by HooRin** [QwenLM/Qwen#1073]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

/root/.virtualenvs/LLMindCraft-main/bin/python /root/autodl-tmp/LLMindCraft-main/src/qwen_test.py 
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|██████████████████| 6/6 [00:06<00:00,  1.09s/it]
thread '<unnamed>' panicked at src/lib.rs:201:64:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/root/autodl-tmp/LLMindCraft-main/src/qwen_test.py", line 34, in <module>
    result,history = model_qwen.chat(tokenizer_qwen,"你好",history=None)
  File "/root/.cache/huggingface/modules/transformers_modules/auditmodel_5/modeling_qwen.py", line 1145, in chat
    response = decode_tokens(
  File "/root/.cache/huggingface/modules/transformers_modules/auditmodel_5/qwen_generation_utils.py", line 275, in decode_tokens
    return _decode_chatml(
  File "/root/.cache/huggingface/modules/transformers_modules/auditmodel_5/qwen_generation_utils.py", line 244, in _decode_chatml
    trim_decode_tokens = tokenizer.decode(tokens[:eod_token_idx], errors=errors)[raw_text_len:]
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3756, in decode
    return self._decode(
  File "/root/.cache/huggingface/modules/transformers_modules/auditmodel_5/tokenization_qwen.py", line 276, in _decode
    return self.tokenizer.decode(token_ids, errors=errors or self.errors)
  File "/root/miniconda3/lib/python3.8/site-packages/tiktoken/core.py", line 258, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
pyo3_runtime.PanicException: no entry found for key

**Comment by jklj077** [comment]
Based on the provided error log, it appears that the model has generated a token which does not exist within its vocabulary. This is unexpected behavior for official models and suggests an issue with your finetuned model.

When finetuning, if the model generates a non-existent token ID, particularly at the end of the output sequence, a common cause could be related to not training the embedding layer during the finetuning process when starting from a base model. However, please note that this is a likely possibility among several potential causes, and without detailed information about the finetuning setup, it's difficult to pinpoint the exact reason.

To diagnose the problem more accurately, I recommend examining the generated token IDs and verifying whether the invalid ID indeed occurs at the conclusion of the output sequence. Further investigation into the finetuning process, including the configurations used and steps followed, will be necessary to identify the root cause of the issue.

**Comment by HooRin** [comment]
我就是用的finetune_lora_ds.sh进行微调的，单卡微调7b-chat运行fintune就没有这个问题

**Comment by jklj077** [comment]
In the absence of specific information in your previous message, we provided a common cause based on historical trends (<https://github.com/QwenLM/Qwen/issues/633> and <https://github.com/QwenLM/Qwen/issues/622>). It's essential to note that optimizing for single-GPU and multi-GPU environments are indeed distinct processes and Qwen-7B-Chat and Qwen-14B-Chat are different models. If you'd like our assistance in examining an issue that you've personally encountered, and not just a general discussion, please adhere to the following instructions:

- To help us accurately investigate and troubleshoot the unique issue you're facing, kindly provide detailed information about your setup (**Steps to Reproduce** and **Environment**). This will enable us to reproduce the scenario and offer tailored advice.
