### ISSUE TITLE
[BUG] <title> OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/.cache/modelscope/qwen/Qwen-7B-Chat.

### ISSUE THREAD

**Issue by cheng18175030250** [QwenLM/Qwen#1118]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1

### 期望行为 | Expected Behavior

1

### 运行环境 | Environment

```Markdown
- OS:1
- Python:1
- Transformers:1
- PyTorch:1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):1
```

### 备注 | Anything else?

使用qwen-7B-chat模型在魔搭的示例代码，并且已经将模型更新到v1.1.9，仍会出现“OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/.cache/modelscope/qwen/Qwen-7B-Chat.” 该如何解决（qwen-14B-chat模型出现同样问题）

**Comment by cheng18175030250** [comment]
![image](https://github.com/QwenLM/Qwen/assets/53423620/fdfdb53e-8a6d-4803-a216-674c98daeb6c)

**Comment by jklj077** [comment]
Please delete the files at "/mnt/workspace/.cache/modelscope/qwen/Qwen-7B-Chat" and rerun the code due to a failed previous model download. For any ModelScope library issues, seek assistance from <https://github.com/modelscope/modelscope> for a faster response.

由于先前的模型下载失败，请删除"/mnt/workspace/.cache/modelscope/qwen/Qwen-7B-Chat"路径下的文件并重新运行代码。如有与ModelScope库相关的任何问题，请前往<https://github.com/modelscope/modelscope>寻求帮助，以获得更及时的回复。
