### ISSUE TITLE
7B模型推理时生成非有效的idx，应该怎么处理？

### ISSUE THREAD

**Issue by AACengineer** [QwenLM/Qwen#1174]
7B模型的vocab_size是151936（7B），这是为了训练加速从而对齐了128；假设使用greedy_search，如果Argmax的结果是在对齐的idx中（例如151935），那么（1）推理过程是否需要在这一步特殊处理？（2）tokenizer.decoder时，对生成的这一类结果怎么解码？

**Comment by jklj077** [comment]
1. Normally, the model does not generate such token indices, even if you are using greedy search, so nothing needs to be done.
2. It raises errors, because it strongly suggests something is wrong. You need to check if the model is intact, the finetuning is successful, the generation configuration is reasonable, etc.
