### ISSUE TITLE
4张卡为什么没有并发推理

### ISSUE THREAD

**Issue by linzm1007** [QwenLM/Qwen#1179]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

目前是多用户使用，同步推理，使用体验差

### 期望行为 | Expected Behavior

多卡并发推理

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
what framework are you using?

**Comment by linzm1007** [comment]
> what framework are you using?

用的 qwen GitHub 官方的脚本

**Comment by jklj077** [comment]
which one?

**Comment by linzm1007** [comment]
> which one?

[docker_web_demo.sh](https://github.com/QwenLM/Qwen/blob/main/docker/docker_web_demo.sh)

**Comment by jklj077** [comment]
The `web_demo.py` script serves as a demonstrative tool and is explicitly not intended for deployment in a production environment due to its inherent lack of production-grade capabilities. Despite being capable of managing multiple concurrent requests, it doesn't process them simultaneously, instead utilizing a queue mechanism implemented by `gradio`. In terms of GPU utilization, when handling each request, the `transformers` library employs a basic model parallelism approach for multi-GPU inference, meaning that only a single GPU is actively engaged at any given moment.

For deploying a solution in a production setting, this repository does not cater to those requirements, and such tasks should be managed by your IT professionals. As an alternative, consider projects like `FastChat` combined with `vLLM`. This setup allows for parallel execution of multiple requests if your GPU has adequate memory and leverages tensor parallelism, thus maximizing resource utilization by engaging all GPUs concurrently.
