### ISSUE TITLE
How can we use this for image captioning any tutorial or documentation exists? 

### ISSUE THREAD

**Issue by FurkanGozukara** [QwenLM/Qwen#349]
I want to load as 4bit and do image captioning

Any turorial example documentation exists?

**Comment by JianxinMa** [comment]
Please visit https://github.com/QwenLM/Qwen-VL for further details. Kindly note that the official checkpoint for this model is temporarily taken down due to reasons that we are unable to disclose. Fortunately, the community has provided a checkpoint backup that can be found at https://github.com/QwenLM/Qwen-VL/issues/73
