### ISSUE TITLE
[BUG] ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by wrl1224** [QwenLM/Qwen#548]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行cli_demo或者web_demo遇到ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.
求助。

### 期望行为 | Expected Behavior

希望能得到解决办法。

### 复现方法 | Steps To Reproduce

run cli_demo or web_demo
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### 运行环境 | Environment

```Markdown
- OS:windows
- Python:3.9
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

i need help!!!
![QQ图片20231028192125](https://github.com/QwenLM/Qwen/assets/70120540/672fdf28-b7f1-4ee0-af67-491ad6fb1eac)

**Comment by jklj077** [comment]
Please first check if the download files are complete (there should be related logs if errors were encountered, but the provided log is incomplete). In mainland China, accessing huggingface may be unstable. The solution to this problem is provided in README (search for "snapshot_download").

In addition, if you have changed the arguments or the Python scripts, please provide us with more information so we can better help you.

**Comment by yxk9810** [comment]
同遇到这个问题，
transformers:4.32.0 
kaggle notebook: https://www.kaggle.com/code/jackiewu/qwen-int4-finetune

**Comment by Modas-Li** [comment]
same issue when finetune lora

**Comment by danjuan-77** [comment]
> same issue when finetune lora

i think the peft's version caused this, after change the version to this : ` transformers==4.32.0 torch==2.1.2+cu121 torchvision==0.16.2+cu121 peft==0.7.1 ` lora worked

**Comment by jklj077** [comment]
The `peft` version conflict, as detailed in the README file, was anticipated to arise no earlier than January 30th, 2024.

![image](https://github.com/QwenLM/Qwen/assets/17811943/b7aab3b2-4851-453d-9cc2-5cb91354153b)

However, this issue has surfaced significantly sooner than that, suggesting a different cause, most probably due to the similar use of `from_pretrained` without `trust_remote_code=True`.

Since the release of Qwen1.5, `trust_remote_code=True` is no longer a must because it is intergrated into the `transformers` codebase. For more information about this integration, discussions on how to leverage Qwen1.5 within the transformers environment, and for updates on community feedback and enhancements, please visit the official Qwen1.5 GitHub repository at https://github.com/QwenLM/Qwen1.5.

**Comment by zixiaotan21** [comment]
Encounted the same problem. I just upgraded the transformer to 4.38.0, 4.38.2, or 4.39.0. But all these endeavors fell to succeed. I wonder how to upgrade the accelerate (to 0.27.2)? Many thanks!

> Just encounted the same problem. I just upgraded the transformer (to 4.38.2) and accelerate (to 0.27.2), then the model loads up successfully.
