### ISSUE TITLE
main branch model error

### ISSUE THREAD

**Issue by zhaotianxiang** [QwenLM/Qwen#586]
<img width="1783" alt="截屏2023-11-05 22 10 58" src="https://github.com/QwenLM/Qwen-Agent/assets/28392282/446a9d8b-d2e0-4c50-a52b-0399714ee185">

Hi， i am using the latest codes and checkpoints， model is QWen/QWen-14B-Chat

is there has a handsome guy to help me figure out what the problem is?

```
- OS: mac m1
- Python:3.10
```

**Comment by jklj077** [comment]
Hi, could you please provide the following information, so that we can better investigate this problem:
1. Are you using a local snapshot or a hub model? (note: "Qwen" instead of "QWen")
2. The version of `transformers` and `pytorch`.
3. If you are using a local snapshot, the files contained in the snapshot.

**Comment by BlueBubbleWei** [comment]
same as mac M1
- OS: mac m1
- Python:3.10
- change model position
- transformers '4.32.0'
- torch.__version__
'2.2.1'


the same error
if param_device_map[p] == "disk"
KeyError: 'lm_head.weight'
