### ISSUE TITLE
💡 [REQUEST] Guide documents related with Qwen Tokenizer and chatml

### ISSUE THREAD

**Issue by dsdanielpark** [QwenLM/Qwen#612]
### 摘要 | Summary

Hello. First of all, I would like to express my respect for the excellent models and the release of open source projects by the Qwen team. I am contacting you because I need help. While training with a Korean dataset, I was inspired by the Qwen paper and would like to revise the tokenizer and dataset once again.

1. I'm curious whether all the different models of Qwen used the same tokenizer. Is this perhaps the reason why the qwen code was separated, due to the tokenizer?
2. If you used different tokenizers, I am curious about how you configured them. If I want to use the Qwen tokenizer with a modified Korean vocabulary, do you have any recommended guidelines or methods?
3. According to the paper, it seems that training in the chatml style results in better token alignment. If this is correct, could you possibly share an example of how you processed the data in the chatml style? Would there have been a significant difference in performance in preliminary experiments compared to datasets used for fine-tuning something like llama2?

Once again, I express my admiration for the amazing work of the Qwen team and my astonishment. Thank you.

### 基本示例 | Basic Example

1. Guide documents - Qwen tokenizer
from cl100k to qwen tokenizer

2. Chatml style Dataset example of Qwen
    ```
    [
     {"token": "<|im_start|>"},
     "system\nYou are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: 2023-03-01",
     {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
     "user\nHow are you",
     {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
     "assistant\nI am doing well!",
     {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
     "user\nHow are you now?",
     {"token": "<|im_end|>"}, "\n"
    ]
    ```

### 缺陷 | Drawbacks

This allows more developers to better understand Qwen. Thank you in advance.

**Comment by jklj077** [comment]
Hi, thank you very much for the support!

> Whether all the different models of Qwen used the same tokenizer? Is this perhaps the reason why the qwen code was separated, due to the tokenizer?
   
In fact, the series of open-sourced Qwen models use the same tokenizer. The code is separated because we currently cannot merge with the main branch of transformers and we actually store the **same** code in different HuggingFace/ModelScope repos (for ease of use).

> Guide documents - Qwen tokenizer

Please see if the [tokenizer note](https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md) could help.

> If I want to use the Qwen tokenizer with a modified Korean vocabulary, do you have any recommended guidelines or methods?

We have provide instructions for expanding the vocabulary at [here](https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md#vocabulary-expansion). The example uses qwen.tiktoken as the base vocabulary. I think it applies to using cl100k as the base as well (some tweaking of the indices are required which is mentioned in the instructions).

> could you possibly share an example of how you processed the data in the chatml style/Chatml style Dataset example of Qwen

Please refer to the finetuning part of the README. We haven't use exactly the chatml style as the source dataset format. The source dataset format is coverted to a chatml-like format in fine-tuning, the code of which is provided in the finetuning script.
<https://github.com/QwenLM/Qwen/blob/99cacff46a2264d1eb187c0a41dcea21fc01f542/finetune.py#L125-L176>
It should be a good start.

> Would there have been a significant difference in performance in preliminary experiments compared to datasets used for fine-tuning something like llama2?

Unfortunately, we are unable to provide more information regarding this question other than what was disclosed in the technical report. It is obvious that different models use different format and they all seem to achieve the goal. The unique characteristic of the chatml format (or any other format that uses special tokens to signify meta-information of a dialogue instead of natural language templates) is that the models are less likely to be attacked using natural language injections similar to SQL injections as explained in OpenAI documentation.

**Comment by dsdanielpark** [comment]
I sincerely appreciate your detailed and prompt response. It was very helpful with the detailed explanation!

This question is also very sensitive so I would be grateful if you could answer it carefully.

It seems that other teams, like the Qwen team, are also attempting to overcome the drawbacks of vanilla attention. Notably, the Mistral and Zephyr teams! Is the Qwen team also experimenting with methods not mentioned in the paper? I think it would be beneficial if Qwen's subsequent papers or reports included a qualitative and quantitative comparison experiment with method of the Mistral and Zephyr teams.

Moreover, I am currently preparing to start training by mixing the strategies of Qwen, Mistral, and Zephyr teams with a large volume of high-quality data refined under a commercially usable license in Korea. Until now, I have spent a lot of time refining the data while checking which datasets could effectively update the weights of llama2.

I hope there will be opportunities for personal and academic collaboration with the Qwen team or university teams in China in the future. I always admire the amazing presentations and open-source projects of the Chinese research teams.
