### ISSUE TITLE
💡 [REQUEST] - Questions Regarding the Release Date of RLHF and the Application of DPO

### ISSUE THREAD

**Issue by dsdanielpark** [QwenLM/Qwen#628]
### 摘要 | Summary

Hello,
I have been reviewing the excellent projects by the Qwen team. Thank you for your work.

1. As mentioned in the README, I am curious about the scheduled release date of the Qwen team's RLHF model.

2. Also, do the Qwen general model and the Qwen-chat model use the same template? I am wondering if the same template was applied to the training as well.

3. Lastly, given the processed data by Qwen, it seems quite feasible to quickly apply DPO (Directed Preference Optimization). Are you not considering the application of DPO? If not, I am curious about the reasons.

4. Is there any information or additional technical reports on the tokenizers used in Qwen chat and Qwen coder? It would be very helpful to have detailed information on how the tokenizers differ for each model.

Thank you in advance for your response.

### 基本示例 | Basic Example

N/A

### 缺陷 | Drawbacks

N/A

**Comment by jklj077** [comment]
1. According to available information, the Qwen-Chat-RLHF models mentioned in the technical report is not currently planned for public release.
2. The Qwen base/general models, by design, does not incorporate templates in its training.
3. We have recently made available [Qwen1.5](https://github.com/QwenLM/Qwen1.5), featuring chat models that has been developed with DPO. It's ready to be interacted with; give it a try!
4. In the technical report, the Code-Qwen models utilize the same tokenizer as those used in the standard Qwen models. For more details on the tokenization process, you can refer to the documentation found at <https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md>.

**Comment by dsdanielpark** [comment]
[jklj077](https://github.com/jklj077)

Thank you for your kind response!
